# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jet2Travel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jet2Travel
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'Jet2TravelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Jet2TravelUITests' do
    # Pods for testing
  end

end
